apiVersion: v1
kind: Secret
metadata:
  name: flask-mongo-secret
  namespace: flask-mongo-ns
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvOm1vbmdvMTIzQG1vbmdvLXNlcnZpY2U6MjcwMTcvZmxhc2tfZGI/YXV0aFNvdXJjZT1hZG1pbg==
