apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: flask-mongo-ns
type: Opaque
data:
  mongo-root-username: bW9uZ28=       # "mongo"
  mongo-root-password: bW9uZ28xMjM=   # "mongo123"
